#pragma once

#define RED_VERSION_STRING "0.0.1"

// Choose one of the three
#define RED_C_BACKEND 0
#define RED_LLVM_BACKEND 0
#define RED_SELF_BACKEND 0
#define RED_LLVM_EXPERIMENTS 1

#define RED_JIT 1

#define RED_SRC_FILE_VERBOSE 0
#define RED_ALLOCATION_VERBOSE 0
#define RED_LEXER_VERBOSE 0
#define RED_PARSER_VERBOSE 0
#define RED_IR_VERBOSE 0
#define RED_LLVM_VERBOSE 1
#define RED_CWD_VERBOSE 0
#define RED_TIMESTAMPS 1

#define RED_BUFFER_MEM_CHECK 0

#define RED_CUSTOM_ALLOCATOR 1
